### 이메일 검증
POST http://localhost:8080/account/email
Content-Type: application/json

{
  "email":"brightdev.bs@gmail.com"
}

### 회원가입
POST http://localhost:8080/account/signup
Content-Type: application/json

{
  "email": "brightdev.bs@gmail.com",
  "password": "password",
  "username": "techbear"
}