server:
  servlet:
    session:
      timeout: 3d

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: local
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: redis
    redis:
      namespace: kmall
  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: kmall.official.cs@gmail.com
    password: neysinqavdzkcttx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jpa:
    #    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size:  100
        highlight_sql: true
        format_sql: true
#        generate_statistics: true
        javax.cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: ehcache.xml
        cache:
          use_second_level_cache: true
          region.factory_class: jcache



#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace

host: localhost:8080/
front-server: http://localhost:3000
logging:
  level:
    root: info
