spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: local
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: kmall.official.cs@gmail.com
    password: neysinqavdzkcttx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jpa:
    #    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size:  100
        format_sql: true